# Site settings
baseURL = "https://mehdi-lembarki.netlify.app"
languageCode = "en-us"
title = "Mehdi Lembarki Kadiry"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Your name"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Mehdi Lembarki Kadiry"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"

    [[params.navigation.links]]
      name = "Generic Blog"
      url = "blogs/ipsum"

    [[params.navigation.links]]
      name = "Elements"
      url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "blogs"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Log In"
      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Mehdi"
    subtitle = "Look around"
    buttonText = "Start"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Movies analysis"
      subtitle = "IMDB ratings"
      image = "pic11.jpg"
      url = "blogs/movies"

    [[params.tiles.showcase]]
      title = "Beer, Wine And Spirits"
      subtitle = "Where Do People Drink The Most Beer, Wine And Spirits?"
      image = "pic02.jpg"
      url = "blogs/spirits"

    [[params.tiles.showcase]]
      title = "US elections "
      subtitle = "Analysis of US elections  "
      image = "pic03.jpg"
      url = "blogs/elections"

    [[params.tiles.showcase]]
      title = "Airbnb in Copenhagen"
      subtitle = "Price for 2 people during 4 nights"
      image = "pic04.jpg"
      url = "blogs/copenhagen"


    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Massa libero"
    subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. 
    Mauris aliquet magna magna sed nunc rhoncus pharetra. 
    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. 
    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "mehdil.mam2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+44 (0)20 7000 7000"

    [[params.contact.address]]
    title = "Address"
    street = "Regent's Park"
    city = "London, NW1 4SA"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Company Name"

    # Uses font awesome icons
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/mehdilembarki"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "www.linkedin.com/in/mehdi-lembarki-kadiri-59713b166"
      label = "LinkedIn"

